<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_antibot"
 *
 * Auto generated by Extension Builder 2015-08-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'tollwerk Anti-Spambot tools',
	'description' => 'Validators and tools for protecting forms against spambots',
	'category' => 'plugin',
	'author' => 'Josch',
	'author_email' => 'joschi@tollwerk.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.2.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1.0-7.9.99',
			'extbase' => '6.1.0-7.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
