<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_antibot"
 *
 * Auto generated by Extension Builder 2018-12-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'tollwerk Antibot',
    'description' => 'Death to Spambots! — CAPTCHA-less spam security for TYPO3 forms',
    'category' => 'plugin',
    'author' => 'Joschi Kuphal',
    'author_email' => 'joschi@tollwerk.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.4.0-',
            'form' => '9.4.0-',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
